project:
  type: website

website:
  title: "alex choi"
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
      - blog.qmd

format:
  html:
    theme:
      - sandstone
    css: styles.css
    toc: true
