project:
  type: website

website:
  title: "alex choi"
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
      - blog.qmd
      - demos.qmd
  page-footer:
    right:
      - icon: envelope-fill
        href: mailto:contact@alexchoi.me
      - icon: github
        href: https://github.com/aechoi
      - icon: linkedin
        href: https://www.linkedin.com/in/alexander-choi/
    border: true
    background: dark
  repo-url: https://www.github.com/aechoi/blog

format:
  html:
    theme:
      - sandstone
    css: styles.css
    toc: true
